
CREATE TABLE COUNTRY (
    COUNTRY_CODE    CHAR(3) NOT NULL PRIMARY KEY,
    COUNTRY_NAME    VARCHAR(255) NOT NULL
);
CREATE INDEX IX_COUNTRY_001 ON COUNTRY(COUNTRY_NAME);

CREATE TABLE REGION (
    ID              INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    COUNTRY         CHAR(3) NOT NULL,
    REGION_NAME     VARCHAR(256) NOT NULL
);
CREATE UNIQUE INDEX IX_REGION_001 ON REGION(COUNTRY,REGION_NAME);
ALTER TABLE REGION ADD CONSTRAINT FK_REGION_001 FOREIGN KEY(COUNTRY) REFERENCES COUNTRY(COUNTRY_CODE);

-- AT = Astronomical Twilight
-- NT = Nautical Twilight
-- CT = Civil Twilight

CREATE TABLE SUN_DATA(
    ID              INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DATA_DATE       DATETIME NOT NULL,
    COUNTRY         CHAR(3) NOT NULL,
    REGION          INTEGER NULL,
    CITY            VARCHAR(256) NOT NULL,
    SUN_RISE        TIME NOT NULL,
    SUN_SET         TIME NOT NULL,
    SUNRISE_ANGLE   FLOAT NOT NULL,
    SUNSET_ANGLE    FLOAT NOT NULL,
    AT_START        TIME NOT NULL,
    AT_END          TIME NOT NULL,
    NT_START        TIME NOT NULL,
    NT_END          TIME NOT NULL,
    CT_START        TIME NOT NULL,
    CT_END          TIME NOT NULL,
    SOLAR_NOON      TIME NOT NULL,
    SN_ANGLE        FLOAT NOT NULL
);
ALTER TABLE SUN_DATA ADD CONSTRAINT FK_SUN_DATA_001 FOREIGN KEY(COUNTRY) REFERENCES COUNTRY(COUNTRY_CODE);
ALTER TABLE SUN_DATA ADD CONSTRAINT FK_SUN_DATA_002 FOREIGN KEY(REGION) REFERENCES REGION(ID);

INSERT INTO COUNTRY(COUNTRY_CODE,COUNTRY_NAME) VALUES('AUS', 'Australia');
INSERT INTO REGION(COUNTRY,REGION_NAME) VALUES('AUS','ACT');
INSERT INTO REGION(COUNTRY,REGION_NAME) VALUES('AUS','NSW');
INSERT INTO REGION(COUNTRY,REGION_NAME) VALUES('AUS','NT');
INSERT INTO REGION(COUNTRY,REGION_NAME) VALUES('AUS','QLD');
INSERT INTO REGION(COUNTRY,REGION_NAME) VALUES('AUS','SA');
INSERT INTO REGION(COUNTRY,REGION_NAME) VALUES('AUS','TAS');
INSERT INTO REGION(COUNTRY,REGION_NAME) VALUES('AUS','VIC');
INSERT INTO REGION(COUNTRY,REGION_NAME) VALUES('AUS','WA');
